// Generated by the protocol buffer compiler. DO NOT EDIT!
// Source: ai_activity

#ifndef PROTOBUF_ai_activity_BOOST_PYTHON_INCLUDED
#define PROTOBUF_ai_activity_BOOST_PYTHON_INCLUDED

#endif // PROTOBUF_ai_activity.proto_BOOST_PYTHON_INCLUDED
