// Generated by the protocol buffer compiler. DO NOT EDIT!
// Source: dota_commonmessages

#ifndef PROTOBUF_dota_commonmessages_BOOST_PYTHON_INCLUDED
#define PROTOBUF_dota_commonmessages_BOOST_PYTHON_INCLUDED

class_<CDOTAMsg_LocationPing>("CDOTAMsg_LocationPing")
	.def("has_x", &CDOTAMsg_LocationPing::has_x)
	.def("x", &CDOTAMsg_LocationPing::x)
	.def("clear_x", &CDOTAMsg_LocationPing::clear_x)
	.def("has_y", &CDOTAMsg_LocationPing::has_y)
	.def("y", &CDOTAMsg_LocationPing::y)
	.def("clear_y", &CDOTAMsg_LocationPing::clear_y)
	.def("has_target", &CDOTAMsg_LocationPing::has_target)
	.def("target", &CDOTAMsg_LocationPing::target)
	.def("clear_target", &CDOTAMsg_LocationPing::clear_target)
	.def("has_direct_ping", &CDOTAMsg_LocationPing::has_direct_ping)
	.def("direct_ping", &CDOTAMsg_LocationPing::direct_ping)
	.def("clear_direct_ping", &CDOTAMsg_LocationPing::clear_direct_ping)
	.def("has_type", &CDOTAMsg_LocationPing::has_type)
	.def("type", &CDOTAMsg_LocationPing::type)
	.def("clear_type", &CDOTAMsg_LocationPing::clear_type)
;

class_<CDOTAMsg_ItemAlert>("CDOTAMsg_ItemAlert")
	.def("has_x", &CDOTAMsg_ItemAlert::has_x)
	.def("x", &CDOTAMsg_ItemAlert::x)
	.def("clear_x", &CDOTAMsg_ItemAlert::clear_x)
	.def("has_y", &CDOTAMsg_ItemAlert::has_y)
	.def("y", &CDOTAMsg_ItemAlert::y)
	.def("clear_y", &CDOTAMsg_ItemAlert::clear_y)
	.def("has_itemid", &CDOTAMsg_ItemAlert::has_itemid)
	.def("itemid", &CDOTAMsg_ItemAlert::itemid)
	.def("clear_itemid", &CDOTAMsg_ItemAlert::clear_itemid)
;

class_<CDOTAMsg_MapLine>("CDOTAMsg_MapLine")
	.def("has_x", &CDOTAMsg_MapLine::has_x)
	.def("x", &CDOTAMsg_MapLine::x)
	.def("clear_x", &CDOTAMsg_MapLine::clear_x)
	.def("has_y", &CDOTAMsg_MapLine::has_y)
	.def("y", &CDOTAMsg_MapLine::y)
	.def("clear_y", &CDOTAMsg_MapLine::clear_y)
	.def("has_initial", &CDOTAMsg_MapLine::has_initial)
	.def("initial", &CDOTAMsg_MapLine::initial)
	.def("clear_initial", &CDOTAMsg_MapLine::clear_initial)
;

class_<CDOTAMsg_WorldLine>("CDOTAMsg_WorldLine")
	.def("has_x", &CDOTAMsg_WorldLine::has_x)
	.def("x", &CDOTAMsg_WorldLine::x)
	.def("clear_x", &CDOTAMsg_WorldLine::clear_x)
	.def("has_y", &CDOTAMsg_WorldLine::has_y)
	.def("y", &CDOTAMsg_WorldLine::y)
	.def("clear_y", &CDOTAMsg_WorldLine::clear_y)
	.def("has_z", &CDOTAMsg_WorldLine::has_z)
	.def("z", &CDOTAMsg_WorldLine::z)
	.def("clear_z", &CDOTAMsg_WorldLine::clear_z)
	.def("has_initial", &CDOTAMsg_WorldLine::has_initial)
	.def("initial", &CDOTAMsg_WorldLine::initial)
	.def("clear_initial", &CDOTAMsg_WorldLine::clear_initial)
	.def("has_end", &CDOTAMsg_WorldLine::has_end)
	.def("end", &CDOTAMsg_WorldLine::end)
	.def("clear_end", &CDOTAMsg_WorldLine::clear_end)
;

class_<CDOTAMsg_SendStatPopup>("CDOTAMsg_SendStatPopup")
	.def("has_style", &CDOTAMsg_SendStatPopup::has_style)
	.def("style", &CDOTAMsg_SendStatPopup::style)
	.def("clear_style", &CDOTAMsg_SendStatPopup::clear_style)
	.def("stat_strings_size", &CDOTAMsg_SendStatPopup::stat_strings_size)
	.def("clear_stat_strings", &CDOTAMsg_SendStatPopup::clear_stat_strings)
	.def("stat_images_size", &CDOTAMsg_SendStatPopup::stat_images_size)
	.def("clear_stat_images", &CDOTAMsg_SendStatPopup::clear_stat_images)
;

class_<CDOTAMsg_CoachHUDPing>("CDOTAMsg_CoachHUDPing")
	.def("has_x", &CDOTAMsg_CoachHUDPing::has_x)
	.def("x", &CDOTAMsg_CoachHUDPing::x)
	.def("clear_x", &CDOTAMsg_CoachHUDPing::clear_x)
	.def("has_y", &CDOTAMsg_CoachHUDPing::has_y)
	.def("y", &CDOTAMsg_CoachHUDPing::y)
	.def("clear_y", &CDOTAMsg_CoachHUDPing::clear_y)
	.def("has_tgtpath", &CDOTAMsg_CoachHUDPing::has_tgtpath)
	.def("tgtpath", &CDOTAMsg_CoachHUDPing::tgtpath, return_value_policy<copy_const_reference>())
	.def("clear_tgtpath", &CDOTAMsg_CoachHUDPing::clear_tgtpath)
;

#endif // PROTOBUF_dota_commonmessages.proto_BOOST_PYTHON_INCLUDED
