// Generated by the protocol buffer compiler. DO NOT EDIT!
// Source: networkbasetypes

#ifndef PROTOBUF_networkbasetypes_BOOST_PYTHON_INCLUDED
#define PROTOBUF_networkbasetypes_BOOST_PYTHON_INCLUDED

class_<CMsgVector>("CMsgVector")
	.def("has_x", &CMsgVector::has_x)
	.def("x", &CMsgVector::x)
	.def("clear_x", &CMsgVector::clear_x)
	.def("has_y", &CMsgVector::has_y)
	.def("y", &CMsgVector::y)
	.def("clear_y", &CMsgVector::clear_y)
	.def("has_z", &CMsgVector::has_z)
	.def("z", &CMsgVector::z)
	.def("clear_z", &CMsgVector::clear_z)
;

class_<CMsgVector2D>("CMsgVector2D")
	.def("has_x", &CMsgVector2D::has_x)
	.def("x", &CMsgVector2D::x)
	.def("clear_x", &CMsgVector2D::clear_x)
	.def("has_y", &CMsgVector2D::has_y)
	.def("y", &CMsgVector2D::y)
	.def("clear_y", &CMsgVector2D::clear_y)
;

class_<CMsgQAngle>("CMsgQAngle")
	.def("has_x", &CMsgQAngle::has_x)
	.def("x", &CMsgQAngle::x)
	.def("clear_x", &CMsgQAngle::clear_x)
	.def("has_y", &CMsgQAngle::has_y)
	.def("y", &CMsgQAngle::y)
	.def("clear_y", &CMsgQAngle::clear_y)
	.def("has_z", &CMsgQAngle::has_z)
	.def("z", &CMsgQAngle::z)
	.def("clear_z", &CMsgQAngle::clear_z)
;

class_<CSVCMsg_GameEvent_key_t>("CSVCMsg_GameEvent_key_t")
	.def("has_type", &CSVCMsg_GameEvent_key_t::has_type)
	.def("type", &CSVCMsg_GameEvent_key_t::type)
	.def("clear_type", &CSVCMsg_GameEvent_key_t::clear_type)
	.def("has_val_string", &CSVCMsg_GameEvent_key_t::has_val_string)
	.def("val_string", &CSVCMsg_GameEvent_key_t::val_string, return_value_policy<copy_const_reference>())
	.def("clear_val_string", &CSVCMsg_GameEvent_key_t::clear_val_string)
	.def("has_val_float", &CSVCMsg_GameEvent_key_t::has_val_float)
	.def("val_float", &CSVCMsg_GameEvent_key_t::val_float)
	.def("clear_val_float", &CSVCMsg_GameEvent_key_t::clear_val_float)
	.def("has_val_long", &CSVCMsg_GameEvent_key_t::has_val_long)
	.def("val_long", &CSVCMsg_GameEvent_key_t::val_long)
	.def("clear_val_long", &CSVCMsg_GameEvent_key_t::clear_val_long)
	.def("has_val_short", &CSVCMsg_GameEvent_key_t::has_val_short)
	.def("val_short", &CSVCMsg_GameEvent_key_t::val_short)
	.def("clear_val_short", &CSVCMsg_GameEvent_key_t::clear_val_short)
	.def("has_val_byte", &CSVCMsg_GameEvent_key_t::has_val_byte)
	.def("val_byte", &CSVCMsg_GameEvent_key_t::val_byte)
	.def("clear_val_byte", &CSVCMsg_GameEvent_key_t::clear_val_byte)
	.def("has_val_bool", &CSVCMsg_GameEvent_key_t::has_val_bool)
	.def("val_bool", &CSVCMsg_GameEvent_key_t::val_bool)
	.def("clear_val_bool", &CSVCMsg_GameEvent_key_t::clear_val_bool)
	.def("has_val_uint64", &CSVCMsg_GameEvent_key_t::has_val_uint64)
	.def("val_uint64", &CSVCMsg_GameEvent_key_t::val_uint64)
	.def("clear_val_uint64", &CSVCMsg_GameEvent_key_t::clear_val_uint64)
;

class_<CSVCMsg_GameEvent>("CSVCMsg_GameEvent")
	.def("has_event_name", &CSVCMsg_GameEvent::has_event_name)
	.def("event_name", &CSVCMsg_GameEvent::event_name, return_value_policy<copy_const_reference>())
	.def("clear_event_name", &CSVCMsg_GameEvent::clear_event_name)
	.def("has_eventid", &CSVCMsg_GameEvent::has_eventid)
	.def("eventid", &CSVCMsg_GameEvent::eventid)
	.def("clear_eventid", &CSVCMsg_GameEvent::clear_eventid)
	.def("keys_size", &CSVCMsg_GameEvent::keys_size)
	.def("clear_keys", &CSVCMsg_GameEvent::clear_keys)
;

class_<CSVCMsgList_GameEvents_event_t>("CSVCMsgList_GameEvents_event_t")
	.def("has_tick", &CSVCMsgList_GameEvents_event_t::has_tick)
	.def("tick", &CSVCMsgList_GameEvents_event_t::tick)
	.def("clear_tick", &CSVCMsgList_GameEvents_event_t::clear_tick)
	.def("has_event", &CSVCMsgList_GameEvents_event_t::has_event)
	.def("event", &CSVCMsgList_GameEvents_event_t::event, return_value_policy<reference_existing_object>())
	.def("clear_event", &CSVCMsgList_GameEvents_event_t::clear_event)
;

class_<CSVCMsgList_GameEvents>("CSVCMsgList_GameEvents")
	.def("events_size", &CSVCMsgList_GameEvents::events_size)
	.def("clear_events", &CSVCMsgList_GameEvents::clear_events)
;

class_<CSVCMsg_UserMessage>("CSVCMsg_UserMessage")
	.def("has_msg_type", &CSVCMsg_UserMessage::has_msg_type)
	.def("msg_type", &CSVCMsg_UserMessage::msg_type)
	.def("clear_msg_type", &CSVCMsg_UserMessage::clear_msg_type)
	.def("has_msg_data", &CSVCMsg_UserMessage::has_msg_data)
	.def("msg_data", &CSVCMsg_UserMessage::msg_data, return_value_policy<reference_existing_object>())
	.def("clear_msg_data", &CSVCMsg_UserMessage::clear_msg_data)
;

class_<CSVCMsgList_UserMessages_usermsg_t>("CSVCMsgList_UserMessages_usermsg_t")
	.def("has_tick", &CSVCMsgList_UserMessages_usermsg_t::has_tick)
	.def("tick", &CSVCMsgList_UserMessages_usermsg_t::tick)
	.def("clear_tick", &CSVCMsgList_UserMessages_usermsg_t::clear_tick)
	.def("has_msg", &CSVCMsgList_UserMessages_usermsg_t::has_msg)
	.def("msg", &CSVCMsgList_UserMessages_usermsg_t::msg, return_value_policy<reference_existing_object>())
	.def("clear_msg", &CSVCMsgList_UserMessages_usermsg_t::clear_msg)
;

class_<CSVCMsgList_UserMessages>("CSVCMsgList_UserMessages")
	.def("usermsgs_size", &CSVCMsgList_UserMessages::usermsgs_size)
	.def("clear_usermsgs", &CSVCMsgList_UserMessages::clear_usermsgs)
;

#endif // PROTOBUF_networkbasetypes.proto_BOOST_PYTHON_INCLUDED
